local PROTOCOL_VERSION = 1

---@class (exact) CMPConstants
---@field PROTOCOL_VERSION CMPVersion
---@field PROTOCOL_VERSION_SIGNATURE CMPVersionSignature
---@field HEADER_OFFSET_PROTOCOL_VERSION_SIGNATURE integer
---@field HEADER_OFFSET_MESSAGE_TYPE integer
local CONSTANTS = {
	PROTOCOL_VERSION = PROTOCOL_VERSION,
	PROTOCOL_VERSION_SIGNATURE = (PROTOCOL_VERSION * 0x9E3779B9 + 0x2D), -- scramble: version * ratio + offset
	HEADER_OFFSET_MESSAGE_TYPE = 31,
	HEADER_OFFSET_PROTOCOL_VERSION_SIGNATURE = 32,
}

return CONSTANTS
