local PROTOCOL_VERSION = 1

---@class (exact) CMPConstants
---@field PROTOCOL_VERSION CMPVersion
---@field PROTOCOL_VERSION_SIGNATURE CMPVersionSignature
---@field HEADER_OFFSET_PROTOCOL_VERSION_SIGNATURE integer
---@field HEADER_OFFSET_MESSAGE_TYPE integer
local CONSTANTS = {
	PROTOCOL_VERSION = PROTOCOL_VERSION,
	PROTOCOL_VERSION_SIGNATURE = (PROTOCOL_VERSION * 0x1A3B5C7 + 0x2D) ^ 0x2FA0A3D, -- (version * 26-bit seed + offset) ^ 26-bit mixer
	HEADER_OFFSET_MESSAGE_TYPE = 31,
	HEADER_OFFSET_PROTOCOL_VERSION_SIGNATURE = 32,
}

return CONSTANTS
